targets:
  $default:
    builders:
      riverpod_generator:
        options:
          provider_name_suffix: "Provider" # (default)
          provider_family_name_suffix: "ProviderFamily" 
    sources:
      - $package$
      - lib/**
      - stories/**
